# This override file should be used when running automated tests so
# that test output is saved to the host

services:
  fcp-pds-web:
    build:
      target: development
    image: fcp-pds-web-development
    container_name: fcp-pds-web-test
    depends_on:
      - fcp-pds-web-postgres
      - ffc-pay-event-store-azurite
    command: npm run test
    volumes:
      - ./app:/home/node/app
      - ./test:/home/node/test
      - ./test-output:/home/node/test-output
      - ./jest.config.js:/home/node/jest.config.js
      - ./package.json:/home/node/package.json
    environment:
      NODE_OPTIONS: "$NODE_OPTIONS --experimental-vm-modules"
      PAY_EVENT_STORE_AZURE_STORAGE_CONNECTION_STRING: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://ffc-pay-event-store-azurite:10000/devstoreaccount1;
      PAY_INJECTION_AZURE_STORAGE_CONNECTION_STRING: DefaultEndpointsProtocol=http;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;AccountName=devstoreaccount1;BlobEndpoint=http://ffc-pay-injection-azurite:10000/devstoreaccount1;
      DOC_AZURE_STORAGE_CONNECTION_STRING: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://ffc-doc-statement-azurite:10000/devstoreaccount1;
      PDS_AZURE_STORAGE_CONNECTION_STRING: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://fcp-pds-data-retention-azurite:10000/devstoreaccount1;
      AUTHENTICATION_ENABLED: "true"
      AZUREID_CLIENT_SECRET: itsasecretshhhhhhhh
      AZUREID_CLIENT_ID: NCC-1701-D
      AZUREID_TENANT_ID: C3PO-R2D2
      REDIRECT_URL: http://thesearenotthedroidsyouarelookingfor

  fcp-pds-web-postgres:
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ffc-pay-event-store-azurite:
    labels:
      com.docker.compose.pay.role: test

networks:
  docs:
    name: docs
    external: false

volumes:
  postgres_data:
