services:
  fcp-pds-web:
    build:
      context: .
      target: production
    image: fcp-pds-web
    container_name: fcp-pds-web
    depends_on:
      - fcp-pds-web-postgres
      - ffc-pay-event-store-azurite
    environment:
      APPINSIGHTS_CLOUDROLE: fcp-pds-web-local
      APPLICATIONINSIGHTS_CONNECTION_STRING: ${APPLICATIONINSIGHTS_CONNECTION_STRING}
      POSTGRES_DB: fcp_pds_web
      POSTGRES_HOST: ${POSTGRES_HOST:-fcp-pds-web-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_SCHEMA_PASSWORD:-ppp}
      POSTGRES_PORT: 5432
      POSTGRES_SCHEMA_NAME: ${POSTGRES_SCHEMA_NAME:-public}
      POSTGRES_USERNAME: ${POSTGRES_SCHEMA_USERNAME:-postgres}
      AZURE_STORAGE_USE_CONNECTION_STRING: "true"
      AZURE_STORAGE_CREATE_CONTAINERS: "true"
      COOKIE_PASSWORD: cookiecookiecookiecookiecookiecookie

  fcp-pds-web-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: fcp_pds_web
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres

  ffc-pay-event-store-azurite:
    image: mcr.microsoft.com/azure-storage/azurite:3.35.0
    command: "azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0 --skipApiVersionCheck"
    labels:
      com.docker.compose.pay.role: ffc-pay-event-store-azurite
