# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  fcp-pds-web:
    build:
      target: development
    image: fcp-pds-web-development
    container_name: fcp-pds-web-development
    ports:
      - "3023:3023"
      - "9229:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
    networks:
      - fcp-pds-web
    environment:
      PAY_EVENT_STORE_AZURE_STORAGE_CONNECTION_STRING: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://ffc-pay-event-store-azurite:10000/devstoreaccount1;
      PAY_INJECTION_AZURE_STORAGE_CONNECTION_STRING: DefaultEndpointsProtocol=http;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;AccountName=devstoreaccount1;BlobEndpoint=http://ffc-pay-injection-azurite:10000/devstoreaccount1;
      DOC_AZURE_STORAGE_CONNECTION_STRING: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://ffc-doc-statement-azurite:10000/devstoreaccount1;
      PDS_AZURE_STORAGE_CONNECTION_STRING: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://fcp-pds-data-retention-azurite:10000/devstoreaccount1;

  fcp-pds-web-postgres:
    ports:
      - "5495:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ffc-pay-event-store-azurite:
    volumes:
      - azurite_data:/data
    ports:
      - "10170:10000"
      - "10171:10001"
      - "10172:10002"

networks:
  fcp-pds-web:
    name: fcp-pds-web
    driver: bridge

volumes:
  azurite_data:
  postgres_data:
