environment: production
environmentCode: dev
ingress:
  class: nginx
  endpoint: fcp-pds-web-dev
  server: azure.defra.cloud
container:
  payEventStoreAzureStorageConnectionString: dummy
  payInjectionAzureStorageConnectionString: dummy
  docAzureStorageConnectionString: dummy
  pdsAzureStorageConnectionString: dummy
  payAzureStorageAccountName: devffcpayst1001
  docAzureStorageAccountName: devffcdocst1001
  azureAppRegistrationRedirectUrl: authenticate

secretProviderClass:
  azure:
    keyvaultName: DEVFFCINFKV1001
    objects:
      - objectName: devtest-ffcahwr-appInsights-connectionString
        objectType: secret
      - objectName: dev-fcp-pds-web-client-secret
        objectType: secret
      - objectName: dev-ffc-pay-cookie-password
        objectType: secret

  secretObjects:
    - secretName: fcp-pds-web
      type: Opaque
      data:
        - objectName: devtest-ffcahwr-appInsights-connectionString
          key: APPLICATIONINSIGHTS_CONNECTION_STRING
        - objectName: dev-fcp-pds-web-client-secret
          key: AZUREID_CLIENT_SECRET
        - objectName: dev-ffc-pay-cookie-password
          key: COOKIE_PASSWORD
