environment: production
environmentCode: dev
ingress:
  class: nginx
  endpoint: ffc-pds-web-dev
  server: azure.defra.cloud
paymentManagementService:
  url: #{container.paymentManagementServiceUrl}#
requestEditorService:
  url: #{container.requestEditorServiceUrl}#
