{{- include "ffc-helm-library.container-config-map" (list . "fcp-pds-web.config-map") -}}
{{- define "fcp-pds-web.config-map" -}}
data:
  NODE_ENV: {{ .Values.environment | quote }}
  PORT: {{ .Values.container.port | quote }}
  APPINSIGHTS_CLOUDROLE: {{ .Chart.Name | quote }}
  AZURE_STORAGE_CONNECTION_STRING: {{ quote .Values.container.azureStorageConnectionString }}
  POSTGRES_DB: {{ quote .Values.postgresService.postgresDb }}
  POSTGRES_HOST: {{ quote .Values.postgresService.postgresqlHost }}
  POSTGRES_PORT: {{ quote .Values.postgresService.postgresPort }}
  POSTGRES_SCHEMA_NAME: {{ quote .Values.postgresService.postgresSchema }}
  POSTGRES_USERNAME: {{ .Values.postgresService.postgresUser | quote }}
  PAY_EVENT_STORE_AZURE_STORAGE_CONNECTION_STRING: {{ quote .Values.container.payEventStoreAzureStorageConnectionString }}
  PAY_INJECTION_AZURE_STORAGE_CONNECTION_STRING: {{ quote .Values.container.payInjectionAzureStorageConnectionString }}
  DOC_AZURE_STORAGE_CONNECTION_STRING: {{ quote .Values.container.docAzureStorageConnectionString }}
  PDS_AZURE_STORAGE_CONNECTION_STRING: {{ quote .Values.container.pdsAzureStorageConnectionString }}
  PAY_AZURE_STORAGE_ACCOUNT_NAME: {{ quote .Values.container.payAzureStorageAccountName }}
  DOC_AZURE_STORAGE_ACCOUNT_NAME: {{ quote .Values.container.docAzureStorageAccountName }}
  AUTHENTICATION_ENABLED: {{ quote .Values.container.azureAppRegistrationEnabled }}
  {{- if .Values.container.azureAppRegistrationEnabled }}
  AZUREID_CLIENT_ID: {{ quote .Values.container.azureAppRegistrationClientId }}
  AZUREID_TENANT_ID: {{ quote .Values.container.azureAppRegistrationTenantId }}
  {{- end }}
  REDIRECT_URL: https://{{ .Values.ingress.endpoint }}.{{ .Values.ingress.server }}/{{ .Values.container.azureAppRegistrationRedirectUrl }}
  SITE_HOSTNAME: https://{{ .Values.ingress.endpoint }}.{{ .Values.ingress.server }}
{{- end -}}
