{{- include "ffc-helm-library.container-config-map" (list . "fcp-pds-web.config-map") -}}
{{- define "fcp-pds-web.config-map" -}}
data:
  NODE_ENV: {{ .Values.environment | quote }}
  PORT: {{ .Values.container.port | quote }}
  APPINSIGHTS_CLOUDROLE: {{ .Chart.Name | quote }}
  AZURE_STORAGE_CONNECTION_STRING: {{ quote .Values.container.azureStorageConnectionString }}
  POSTGRES_DB: {{ quote .Values.postgresService.postgresDb }}
  POSTGRES_HOST: {{ quote .Values.postgresService.postgresqlHost }}
  POSTGRES_PORT: {{ quote .Values.postgresService.postgresPort }}
  POSTGRES_SCHEMA_NAME: {{ quote .Values.postgresService.postgresSchema }}
  POSTGRES_USERNAME: {{ .Values.postgresService.postgresUser | quote }}
{{- end -}}
