name: Secret Scanner

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

jobs:
  secret-scan:
    uses: DEFRA/ffc-shared-actions/.github/workflows/secret-scanner.yml@main
    secrets: inherit
